version: 2
jobs:
   node8:
     docker:
       - image: circleci/node:8
     steps: &steps
       - checkout
       - restore_cache:
           keys:
             - npm-deps-{{ checksum "package.json" }}
       - run: npm install
       - save_cache:
           key: npm-deps-{{ checksum "package.json" }}
           paths:
             - node_modules/
       - run: npm test
   node10:
     docker:
       - image: circleci/node:10
     steps: *steps
  node11:
     docker:
       - image: circleci/node:11
     steps: *steps
   
workflows:
  version: 2
  all_nodes:
    jobs:
      - node8
      - node10
      - node11
       
